loki.source.file "log_file" {
  targets = [{__path__ = "/tmp/log/fiber_example/logs.txt"}]
  forward_to = [loki.process.alloy.receiver]
}

loki.process "alloy" {
  stage.json {
    expressions = {service_name = "", level = "", component = "", adapter = ""}
  }
  stage.labels {
    values = {
      service_name = "",
      level = "",
      component = "",
      adapter = "",
    }
  }

  forward_to = [loki.write.default.receiver]
}

loki.write "default" {
  endpoint {
    url       = "http://gateway:3100/loki/api/v1/push"
    tenant_id = "tenant1"
  }
}
